kind: pipeline
type: docker
name: default
  
steps:
- name: 发布 hello
  image: mcr.microsoft.com/dotnet/sdk:6.0
  pull: if-not-exists
  commands:
  - dotnet restore
  - dotnet publish --no-restore -c Release -o app --no-restore