kind: pipeline
type: docker
name: default

# steps:
# - name: tobuild
  # image: alpine
  # commands:
  # - echo hello
  # - echo world
  
steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - docker build -t test/test1 .
  
- name: run
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - docker run -d -p 8090:5000 test/test1