kind: pipeline
type: docker
name: default
  
steps:
- name: 发布 hello
  image: mcr.microsoft.com/dotnet/sdk:6.0
  pull: if-not-exists
  commands:
  - dotnet restore
  - dotnet publish --no-restore -c Release -o app --no-restore

- name: 构建镜像
  image: plugins/docker
  pull: if-not-exists
  settings:
    mirror: https://nqz266l0.mirror.aliyuncs.com
    registry: 192.168.137.200:5000
    repo: 192.168.137.200:5000/helloworld
    tags: helloworld
    dockerfile: Dockerfile
    context: .
    insecure: true