kind: pipeline
type: docker
name: default

# steps:
# - name: tobuild
  # image: alpine
  # commands:
  # - echo hello
  # - echo world
  
steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet build
  - dotnet test

- name: images
  image: plugins/docker
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  commands:
  - docker build -t test/one .
  
- name: step3
  image: plugins/docker
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  commands:
  - docker run -d -e 8090:5000 test/one